/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.summercoding.bank.ui;

import JFrameSave2;
import com.summercoding.bank.controlleur.Controleur;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LECAUCHY
 */
public class JFramesave2 extends javax.swing.JFrame {
Controleur controleur = new Controleur();
    /**
     * Creates new form JFramesave2
     */
    public JFramesave2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        champjour = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fjmxh = new javax.swing.JLabel();
        champnom = new javax.swing.JTextField();
        champpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        champprenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        champlogin = new javax.swing.JTextField();
        champannuler = new javax.swing.JButton();
        comboboxannee = new javax.swing.JComboBox<>();
        comboboxmois = new javax.swing.JComboBox<>();
        comboboxjour = new javax.swing.JComboBox<>();
        radiobuttonmasculin = new javax.swing.JRadioButton();
        radiobuttonfeminin = new javax.swing.JRadioButton();
        comboboxadmin = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        buttonOk.setText("OK");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        jLabel2.setText("password");

        fjmxh.setText("Nom");

        jLabel4.setText("Prenom");

        jLabel5.setText("Datenaiss");

        jLabel6.setText("Genre");

        jLabel7.setText("Idadmin");

        champannuler.setText("Annuler");
        champannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champannulerActionPerformed(evt);
            }
        });

        comboboxannee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019" }));
        comboboxannee.setToolTipText("");

        comboboxmois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboboxmois.setToolTipText("");

        comboboxjour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        radiobuttonmasculin.setText("Maxculin");
        radiobuttonmasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonmasculinActionPerformed(evt);
            }
        });

        radiobuttonfeminin.setText("Feminin");
        radiobuttonfeminin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonfemininActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout champjourLayout = new javax.swing.GroupLayout(champjour);
        champjour.setLayout(champjourLayout);
        champjourLayout.setHorizontalGroup(
            champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champjourLayout.createSequentialGroup()
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fjmxh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(champjourLayout.createSequentialGroup()
                        .addComponent(champannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOk)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(champjourLayout.createSequentialGroup()
                        .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radiobuttonfeminin)
                            .addComponent(champprenom)
                            .addComponent(champnom)
                            .addComponent(champpassword)
                            .addComponent(champlogin)
                            .addGroup(champjourLayout.createSequentialGroup()
                                .addComponent(comboboxannee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboboxmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboboxjour, 0, 30, Short.MAX_VALUE))
                            .addComponent(radiobuttonmasculin)
                            .addComponent(comboboxadmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        champjourLayout.setVerticalGroup(
            champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(champjourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fjmxh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champnom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxannee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiobuttonmasculin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobuttonfeminin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(champjourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(champannuler)
                    .addComponent(buttonOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(champjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(champjour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        //try
        //{
        String login = champlogin.getText();
        String password = champpassword.getText();//mon getText n'est pas barrer
        String nom = champnom.getText();
        String prenom = champprenom.getText();
        LocalDate datenaiss=LocalDate.of(12, Month.MARCH, 2002);
        //String genre=champgenre.getText();
        //String idadmin=comboboxadmin.getText();
        
        
       // SimpleDateFormat format = new SimpleDateFormat();//convertis la date de String en date
        //LocalDate date = null;
        //try{
          //  date = format.parse(datenaiss);
        //}catch(Exception e){
          //  e.printStackTrace();
        //}
        
        //int id = 0;
        //try{
        //    id = Integer.parseInt(idadmin);
        //    System.out.println(id);
        //}catch(NumberFormatException e){
          //  System.out.println("La chaine n`est pas un entier valide");
        //}
        
        //boolean genre = true;
       // String Genre = Boolean.toString(genre);
        
        // controleur.routeVersSaveUtilisateur(login, password, nom,prenom ,datenaiss ,genre , idadmin);
        //JOptionPane.showMessageDialog(null, "success");
        
        //champlogin.setText("");
        //champpassword.setText("");
        //champnom.setText("");
        //champprenom.setText("");
        //champdatenaiss.setText("");
        //champgenre.setText("");
        //comboboxadmin.setText("");
        //}catch (SQLException ex) {
          //  Logger.getLogger(JFramesave2.class.getName()).log(Level.SEVERE, null, ex);
        //}
        //JOptionPane.showMessageDialog(null, "Echec de la requete");
        
    }//GEN-LAST:event_buttonOkActionPerformed

    private void champannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champannulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_champannulerActionPerformed

    private void radiobuttonfemininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonfemininActionPerformed
        // TODO add your handling code here:
        radiobuttonmasculin.setSelected(false);
    }//GEN-LAST:event_radiobuttonfemininActionPerformed

    private void radiobuttonmasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonmasculinActionPerformed
        // TODO add your handling code here:
        radiobuttonfeminin.setSelected(false);
    }//GEN-LAST:event_radiobuttonmasculinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramesave2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramesave2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramesave2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramesave2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramesave2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton champannuler;
    private javax.swing.JPanel champjour;
    private javax.swing.JTextField champlogin;
    private javax.swing.JTextField champnom;
    private javax.swing.JPasswordField champpassword;
    private javax.swing.JTextField champprenom;
    private javax.swing.JComboBox<String> comboboxadmin;
    private javax.swing.JComboBox<String> comboboxannee;
    private javax.swing.JComboBox<String> comboboxjour;
    private javax.swing.JComboBox<String> comboboxmois;
    private javax.swing.JLabel fjmxh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton radiobuttonfeminin;
    private javax.swing.JRadioButton radiobuttonmasculin;
    // End of variables declaration//GEN-END:variables
}
